server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: docs-route
          uri: lb://keynote-service
          predicates:
            - Path=/keynotes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
